version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - 80:3000
    depends_on: 
      - mongo
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/lazy

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017