import type { Metadata } from 'next';
import { Session } from 'next-auth';
import { Inter } from 'next/font/google';
import React from 'react';

import { Providers } from '@lib/Providers';
import '@styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type TLayoutProps = {
  children: React.ReactNode;
  session: Session | null;
};

const RootLayout = ({ children, session }: TLayoutProps) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
